### ISSUE TITLE
bullet indentation and vertical spacing

### ISSUE THREAD

**Issue by ozanj** [ozanj/naed_presentation#1]
@cyouh95 

Can you increase the indentation [horizontal] from non-bullet to first-level bullet; and the indentation from first-level bullet to second-level bullet? [see first motivation slide]

and can you also increase the vertical space from first-level bullet to second-level bullet [see first motivation slide]

thank you!

**Comment by cyouh95** [comment]
@ozanj How does this look? #4 

![spacing](https://user-images.githubusercontent.com/25449416/48451504-94d9a100-e75f-11e8-8233-e4d6833f7a9a.png)

Not too sure about line spacing! Or does adding horizontal line help?
![line](https://user-images.githubusercontent.com/25449416/48451627-0ca7cb80-e760-11e8-8473-fc0a265f488f.png)

**Comment by ozanj** [comment]
@cyouh95 

looks wonderful! let's go with the option with the horizontal line. maybe make it same color red as slide title?

thank you!!!
