### ISSUE TITLE
add total number of visits to slide titled "deep dive results" that lists all universities

### ISSUE THREAD

**Issue by ozanj** [ozanj/naed_presentation#13]
@cyouh95 

right now it says

North Carolina State University at Raleigh
Rutgers University-New Brunswick
Stony Brook University

want it to say [I'm making up numbers]
North Carolina State University at Raleigh (N=1,000)
Rutgers University-New Brunswick (N=800)
Stony Brook University (N=700)

N would refer to total number of visits across all types. [i'm assuming right now this is just domestic visits, right?]

and links to universities should be blue

**Comment by cyouh95** [comment]
@ozanj This is done - and yup, only 2017 US events!
