### ISSUE TITLE
Font color/boldness/thickness for text within slide

### ISSUE THREAD

**Issue by ozanj** [ozanj/naed_presentation#14]
@cyouh95 

The font style looks beautiful! very easy to read.

my concern is that the font within bullet-points will be hard for people in back go read because it is lighter color.

can you try to have text within bullet-points to be the same font color/thickness/etc as the non-bullteted text

Second, try changing the font on non-bulleted text a little bit to differentiate it from the bulleted text (e.g., a little bit bolder/thicker)

I get that these changes might make text not fit as well. changing text will be my responsibility.

**Comment by cyouh95** [comment]
@ozanj Hope changes look okay! This is now using `regular` for bulleted text and `bold` for non-bulleted text + bolded text #15: https://fonts.google.com/specimen/Open+Sans?selection.family=Open+Sans

Not sure if the `bold` is too bold? There is also a `semi-bold`, but the contrast is not as obvious:
![screen shot 2018-11-14 at 6 09 10 pm](https://user-images.githubusercontent.com/25449416/48525612-a7280d80-e839-11e8-89cb-d218fd0e0bbd.png)

compared to current change - `regular` + `bold`:
![screen shot 2018-11-14 at 6 08 46 pm](https://user-images.githubusercontent.com/25449416/48525635-b9a24700-e839-11e8-9ae9-88582e5c3ffc.png)

**Comment by ozanj** [comment]
Let's go with "semi-bold" for the non-bulleted text. and the full bold for when we explicitly want to bold text [like I did in "research question"
