### ISSUE TITLE
make pop up table of university characteristics

### ISSUE THREAD

**Issue by ozanj** [ozanj/naed_presentation#17]
@cyouh95 

Make pop up table of university characteristics. you will see on presentation where I want it (slide on analysis sample)

**Comment by cyouh95** [comment]
Change table to use `median` instead of `mean`

**Comment by ozanj** [comment]
table looks good. replace with median table.

drop the rows for state appropriations.

keep the rows for total state revenue.

changes in row names:
instead of "total net tuition revenue" should just be "Net tuition revenue"

instead of Total state revenue should be
"Revenue from state (appropriations+grants+contracts)

instead of "Revenue per student" should be "State revenue per student"

Instead of "Percent of total revenue from state (all sources)" should be "Percent of total revenue from state"
