### ISSUE TITLE
reference list

### ISSUE THREAD

**Issue by ozanj** [ozanj/naed_presentation#2]
@cyouh95 

can you create the beginnings of a reference list [e.g., whatever changes need to be made to YAML header]. you can use spencer.bib or whatever it was called.

just add a couple citations to the motivation slide and then I'll insert the rest of the references myself.

actual reference list should be the last slide.

thank you!

**Comment by cyouh95** [comment]
@ozanj Package documentation is here: https://github.com/cboettig/knitcitations
https://cran.r-project.org/web/packages/knitcitations/vignettes/tutorial.pdf
https://cran.r-project.org/web/packages/knitcitations/knitcitations.pdf

**Comment by cyouh95** [comment]
@ozanj We could also add this line in the code chunk under [here](https://github.com/ozanj/naed_presentation/blob/faa61f1cb07df01e8f038701442b7db545d34b43/index.Rmd#L23-L25):
```r
bib <- read.bibtex('./assets/other/spencer-bib.bib')
```

And refer to it by:
```r
`r citep(bib['RN959'])`
```
