### ISSUE TITLE
add link to emra research website

### ISSUE THREAD

**Issue by ozanj** [ozanj/naed_presentation#6]
@cyouh95 

can you add link to emraresearch.org in title slide and on bottom left of every slide?

**Comment by cyouh95** [comment]
@ozanj Currently not in deep-dive slides (because of the select univ button on bottom left) - would we still want to add it? 

And hope the title slide look okay! do we also want website link there? or is the logo enough?

**Comment by ozanj** [comment]
@cyouh95 

can we try it in top right, except in deep dive slides
